import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';

 import '../imports/ui/Others/feed.js';
import '../imports/ui/Facilitator/attendence.js';
import '../imports/ui/Others/body.js';
 import '../imports/ui/Parent/parent.js';
 import '../imports/ui/Parent/changeRequest.js';
 import '../imports/ui/Others/routes.js';
 import '../imports/ui/Admin/admin.js';
 import '../imports/ui/Login/login.js';
 import '../imports/ui/Admin/atten.js';
 import '../imports/ui/Admin/getLgaList.js';
 import '../imports/ui/Admin/googlemaps.js';
 import '../imports/ui/Admin/add_facilitator.js';
 import '../imports/ui/Admin/facilitatorlist.js';
 import '../imports/ui/Admin/addsession.js';
 import '../imports/ui/Admin/sessionlist.js';
 import '../imports/ui/Admin/satisfaction.js';
 import '../imports/ui/Admin/facilitators.js';
import '../imports/ui/Others/feed.js';
import '../imports/ui/Facilitator/attendence.js';
import '../imports/ui/Others/body.js';
import '../imports/ui/Parent/parent.js';
import '../imports/ui/Parent/changeRequest.js';
import '../imports/ui/Others/routes.js';
import '../imports/ui/LGA/addFacilitators.js';
import '../imports/ui/LGA/lgaDashboard.js';
import '../imports/ui/LGA/viewRecords.js';
import '../imports/ui/LGA/allFacilitators.js';
import '../imports/ui/LGA/sessionChangeRequest.js';
import '../imports/ui/Parent/parentGetSession.js';
import '../imports/ui/LGA/lgaReport.js';

